"""Generate research indexes from YAML ledger metadata."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

try:
    from scripts.ledger import LedgerError, read_artifact
except ModuleNotFoundError:  # pragma: no cover - CLI execution fallback
    from ledger import LedgerError, read_artifact

ROOT = Path(__file__).resolve().parents[1]


def _first_heading(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line.removeprefix("# ").strip()
    return path.stem


def _metadata(path: Path) -> dict[str, Any]:
    try:
        return read_artifact(path).metadata
    except LedgerError:
        return {}


def _markdown_link(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _format_list(values: object) -> str:
    if not isinstance(values, list) or not values:
        return "-"
    return ", ".join(f"`{value}`" for value in values)


def _artifact_rows(
    pattern_root: Path,
    pattern: str,
) -> list[tuple[Path, dict[str, Any], str]]:
    return [
        (path, _metadata(path), _first_heading(path))
        for path in sorted(pattern_root.glob(pattern))
        if path.is_file()
    ]


def _experiment_rows() -> list[tuple[Path, dict[str, Any], str]]:
    rows: list[tuple[Path, dict[str, Any], str]] = []
    for path in sorted((ROOT / "experiments").glob("EXP-*")):
        experiment_md = path / "experiment.md"
        if experiment_md.exists():
            rows.append(
                (experiment_md, _metadata(experiment_md), _first_heading(experiment_md))
            )
    return rows


def _section(
    title: str,
    rows: list[tuple[Path, dict[str, Any], str]],
    *,
    include_dependencies: bool = False,
) -> list[str]:
    lines = [f"## {title}", ""]
    if not rows:
        lines.extend(["No entries found.", ""])
        return lines

    if include_dependencies:
        lines.extend(
            [
                "| Artifact | ID | Status | Dependencies | Evidence | Title |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
    else:
        lines.extend(
            ["| Artifact | ID | Status | Title |", "| --- | --- | --- | --- |"]
        )

    for path, metadata, heading in rows:
        link = _markdown_link(path)
        artifact_id = metadata.get("id", path.stem)
        status = metadata.get("status", "unknown")
        if include_dependencies:
            evidence_count = len(metadata.get("evidence", []))
            lines.append(
                f"| [`{link}`]({link}) | `{artifact_id}` | `{status}` | "
                f"{_format_list(metadata.get('depends_on'))} | {evidence_count} | "
                f"{heading} |"
            )
        else:
            lines.append(
                f"| [`{link}`]({link}) | `{artifact_id}` | "
                f"`{status}` | {heading} |"
            )
    lines.append("")
    return lines


def _claim_graph(claims: list[tuple[Path, dict[str, Any], str]]) -> str:
    lines = [
        "# Claim Graph",
        "",
        "Generated by `python scripts/make_index.py`.",
        "",
        "```mermaid",
        "graph TD",
    ]
    edges: list[str] = []
    for _path, metadata, _heading in claims:
        claim_id = metadata.get("id")
        if not isinstance(claim_id, str):
            continue
        lines.append(f'  {claim_id.replace("-", "_")}["{claim_id}"]')
        depends_on = metadata.get("depends_on")
        if isinstance(depends_on, list):
            for dependency in depends_on:
                if isinstance(dependency, str):
                    edges.append(
                        f'  {dependency.replace("-", "_")} --> '
                        f'{claim_id.replace("-", "_")}'
                    )
    lines.extend(edges or ["  empty[\"No claim dependencies recorded\"]"])
    lines.extend(["```", ""])
    return "\n".join(lines)


def _open_gaps(claims: list[tuple[Path, dict[str, Any], str]]) -> str:
    lines = ["# Open Gaps", "", "Generated by `python scripts/make_index.py`.", ""]
    open_rows = [
        (path, metadata, heading)
        for path, metadata, heading in claims
        if metadata.get("status") not in {"checked", "refuted", "abandoned"}
    ]
    if not open_rows:
        lines.extend(["No open claim gaps found.", ""])
    else:
        for path, metadata, heading in open_rows:
            lines.append(
                f"- `{metadata.get('status', 'unknown')}` "
                f"[{metadata.get('id', path.stem)}]({_markdown_link(path)}): {heading}"
            )
        lines.append("")
    return "\n".join(lines)


def _failed_experiments(
    experiments: list[tuple[Path, dict[str, Any], str]]
) -> str:
    lines = [
        "# Failed Experiments",
        "",
        "Generated by `python scripts/make_index.py`.",
        "",
    ]
    failed_rows = [
        (path, metadata, heading)
        for path, metadata, heading in experiments
        if metadata.get("status") in {"failed", "blocked", "obsolete"}
    ]
    if not failed_rows:
        lines.extend(["No failed, blocked, or obsolete experiments found.", ""])
    else:
        for path, metadata, heading in failed_rows:
            lines.append(
                f"- `{metadata.get('status', 'unknown')}` "
                f"[{metadata.get('id', path.parent.name)}]"
                f"({_markdown_link(path)}): {heading}"
            )
        lines.append("")
    return "\n".join(lines)


def _next_actions(
    claims: list[tuple[Path, dict[str, Any], str]],
    reports: list[tuple[Path, dict[str, Any], str]],
) -> str:
    lines = ["# Next Actions", "", "Generated by `python scripts/make_index.py`.", ""]
    action_rows: list[str] = []
    for path, metadata, heading in claims:
        if metadata.get("status") in {
            "idea",
            "conjecture",
            "plausible",
            "proof-draft",
            "blocked",
        }:
            action_rows.append(
                f"- Review `{metadata.get('id', path.stem)}` "
                f"({metadata.get('status', 'unknown')}): "
                f"[{heading}]({_markdown_link(path)})"
            )
    for path, metadata, heading in reports:
        if metadata.get("status") in {"draft", "blocked"}:
            action_rows.append(
                f"- Finish report `{metadata.get('id', path.stem)}` "
                f"({metadata.get('status', 'unknown')}): "
                f"[{heading}]({_markdown_link(path)})"
            )
    lines.extend(action_rows or ["No next actions inferred from ledger status."])
    lines.append("")
    return "\n".join(lines)


def _registry_sections() -> list[str]:
    registry_path = ROOT / "tools" / "registry.yaml"
    if not registry_path.exists():
        return []

    data = yaml.safe_load(registry_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        return []

    lines = ["## Project Skills", ""]
    project_skills = data.get("project_skills", [])
    if isinstance(project_skills, list) and project_skills:
        lines.extend(["| Skill | Status | Tools |", "| --- | --- | --- |"])
        for skill in project_skills:
            if not isinstance(skill, dict):
                continue
            path = skill.get("path")
            skill_id = skill.get("id", "unknown")
            link = path if isinstance(path, str) else ""
            tool_ids = _format_list(skill.get("tool_ids"))
            lines.append(
                f"| [`{skill_id}`]({link}) | `{skill.get('status', 'unknown')}` | "
                f"{tool_ids} |"
            )
    else:
        lines.append("No project skills recorded.")
    lines.append("")

    tools = data.get("tools", [])
    verified_tools = [
        tool
        for tool in tools
        if isinstance(tool, dict) and tool.get("status") == "verified"
    ] if isinstance(tools, list) else []
    lines.extend(["## Verified Tool Routes", ""])
    if verified_tools:
        lines.extend(
            [
                "| Tool | Route | Evidence Mode | Licensed | Expensive |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for tool in verified_tools:
            lines.append(
                f"| `{tool.get('id', 'unknown')}` | "
                f"`{tool.get('route', 'unknown')}` | "
                f"`{tool.get('evidence_mode', 'unknown')}` | "
                f"`{tool.get('licensed', False)}` | "
                f"`{tool.get('expensive', False)}` |"
            )
    else:
        lines.append("No verified tool routes recorded.")
    lines.append("")
    return lines


def _write_generated(path: Path, text: str) -> None:
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def main() -> int:
    claims = _artifact_rows(ROOT / "claims", "CLAIM-*.md")
    plans = _artifact_rows(ROOT / "plans", "PLAN-*.md")
    experiments = _experiment_rows()
    reports = _artifact_rows(ROOT / "reports", "REPORT-*.md")

    lines = [
        "# Research Index",
        "",
        "Generated by `python scripts/make_index.py`.",
        "",
    ]
    lines.extend(_section("Claims", claims, include_dependencies=True))
    lines.extend(_section("Plans", plans))
    lines.extend(_section("Experiments", experiments))
    lines.extend(_section("Reports", reports))
    lines.extend(_registry_sections())

    _write_generated(ROOT / "INDEX.md", "\n".join(lines))
    _write_generated(ROOT / "CLAIM_GRAPH.md", _claim_graph(claims))
    _write_generated(ROOT / "OPEN_GAPS.md", _open_gaps(claims))
    _write_generated(ROOT / "FAILED_EXPERIMENTS.md", _failed_experiments(experiments))
    _write_generated(ROOT / "NEXT_ACTIONS.md", _next_actions(claims, reports))
    print(
        "wrote INDEX.md, CLAIM_GRAPH.md, OPEN_GAPS.md, "
        "FAILED_EXPERIMENTS.md, NEXT_ACTIONS.md"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
