"""Generate INDEX.md from claims, experiments, and reports."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _first_heading(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line.removeprefix("# ").strip()
    return path.stem


def _status(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("Status:"):
            return line.removeprefix("Status:").strip() or "unknown"
    return "unknown"


def _markdown_link(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _section(title: str, rows: list[tuple[Path, str, str]]) -> list[str]:
    lines = [f"## {title}", ""]
    if not rows:
        lines.extend(["No entries found.", ""])
        return lines
    lines.extend(["| Artifact | Status | Title |", "| --- | --- | --- |"])
    for path, status, heading in rows:
        link = _markdown_link(path)
        lines.append(f"| [`{link}`]({link}) | `{status}` | {heading} |")
    lines.append("")
    return lines


def main() -> int:
    claims = [
        (path, _status(path), _first_heading(path))
        for path in sorted((ROOT / "claims").glob("CLAIM-*.md"))
    ]
    experiments = []
    for path in sorted((ROOT / "experiments").glob("EXP-*")):
        experiment_md = path / "experiment.md"
        if experiment_md.exists():
            experiments.append(
                (experiment_md, _status(experiment_md), _first_heading(experiment_md))
            )
    reports = [
        (path, _status(path), _first_heading(path))
        for path in sorted((ROOT / "reports").glob("REPORT-*.md"))
    ]

    lines = [
        "# Research Index",
        "",
        "Generated by `python scripts/make_index.py`.",
        "",
    ]
    lines.extend(_section("Claims", claims))
    lines.extend(_section("Experiments", experiments))
    lines.extend(_section("Reports", reports))

    (ROOT / "INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote INDEX.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
